default:
  models-path:
    default: 'app\models\files\cbi.keras'
    lstm: 'app\models\files\lstm.keras'
    cnn: 'app\models\files\cnn.h5'
    cbi: 'app\models\files\cbi.keras'
  tokenizers-path:
    default: 'app\models\tokenizers\tokenizer2.json'
    cnn: 'app\models\tokenizers\tokenizer1.json'
    lstm: 'app\models\tokenizers\tokenizer2.json'
    cbi: 'app\models\tokenizers\tokenizer2.json'
  kafka:
    port: 9092
    host: 'kafka'
    model: 'CBI' # 'CBI' or 'LSTM' or 'CNN'
    input-topic: 'talkpole_in'
    output-topic: 'talkpole_out'
    group-id: 'talkpole'
    input-schema: 'app\kafka\schema\input.avsc'
    output-schema: 'app\kafka\schema\output.avsc'
test:

dev:

prod: