default:
  models-path:
    default: '/talkpole/app/models/files/cbi.keras'
    lstm: '/talkpole/app/models/files/lstm.keras'
    cnn: '/talkpole/app/models/files/cnn.h5'
    cbi: '/talkpole/app/models/files/cbi.keras'
  tokenizers-path:
    default: '/talkpole/app/models/tokenizers/tokenizer2.json'
    cnn: '/talkpole/app/models/tokenizers/tokenizer1.json'
    lstm: '/talkpole/app/models/tokenizers/tokenizer2.json'
    cbi: '/talkpole/app/models/tokenizers/tokenizer2.json'
  kafka:
    port: 9094
    host: 'kafka'
    model: 'CBI' # 'CBI' or 'LSTM' or 'CNN'
    input-topic: 'talkpole_in'
    output-topic: 'talkpole_out'
    group-id: 'talkpole'
    input-schema: '/talkpole/app/kafka/schema/input.avsc'
    output-schema: '/talkpole/app/kafka/schema/output.avsc'
test:

dev:

prod: