services:
  talkpole:
    container_name: talkpole
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - talkpole
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      retries: 3

networks:
  talkpole:
    driver: bridge


    