name: Deploy UI version

on:
  push:
    branches:
      - main

jobs:
  deploy-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Cache model files
      uses: actions/cache@v3
      with:
        path: ai-models/
        key: ${{ runner.os }}-model-cache
        restore-keys: |
          ${{ runner.os }}-model-cache
    - name: Run Tests
      run: |
        pytest
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/talkpole:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/talkpole:ui-version

